name: Flutter Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  create_env_file:
    runs-on: ubuntu-latest
    steps:
    - name: Create .env file
      run: |
        echo "FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}" >> .env
        echo "FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}" >> .env
        echo "FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" >> .env
        echo "FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" >> .env
        echo "FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }}" >> .env
        echo "FIREBASE_DATABASE_URL=${{ secrets.FIREBASE_DATABASE_URL }}" >> .env
        echo "FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}" >> .env
        echo "FIREBASE_IOS_CLIENT_ID=${{ secrets.FIREBASE_IOS_CLIENT_ID }}" >> .env
        echo "FIREBASE_IOS_BUNDLE_ID=${{ secrets.FIREBASE_IOS_BUNDLE_ID }}" >> .env
    - uses: actions/upload-artifact@v2
      with:
        name: env-file
        path: .env

  build_web:
    needs: create_env_file
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: env-file
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.2'
        channel: 'stable'
    - run: flutter pub get
    - run: flutter build web
    - uses: actions/upload-artifact@v2
      with:
        name: web-build
        path: build/web
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./build/web

  build_android:
    needs: create_env_file
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: env-file
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.2'
        channel: 'stable'
    - run: flutter pub get
    - run: flutter build apk --split-per-abi
    - uses: actions/upload-artifact@v2
      with:
        name: android-build
        path: build/app/outputs/flutter-apk

  build_ios:
    needs: create_env_file
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: env-file
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.2'
        channel: 'stable'
    - run: flutter pub get
    - run: flutter build ios --release --no-codesign
    - uses: actions/upload-artifact@v2
      with:
        name: ios-build
        path: build/ios/iphoneos
